services:
  app:
    build: .
    restart: always
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy 

  test:
    build: .
    container_name: urlShortenerTests
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      sh -c "npm test"

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s   # run every 10 seconds
      timeout: 5s     # fail if it takes more than 5s
      retries: 5      # try 5 times before marking unhealthy
      start_period: 10s  # give MongoDB some time to boot before starting checks
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
